// 示例数据 - 以杨紫为例

import { Work, Schedule, Brand, Magazine, Award, GalleryItem, Stats } from './types';

export const stats: Stats = {
  totalFans: '52,000,000+',
  totalWorks: 65,
  totalBrands: 14,
  totalAwards: 32,
};

export const works: Work[] = [
  // 待播/待拍
  {
    id: 'tv-upcoming-1',
    title: '玉兰花开君再来',
    type: 'tv',
    status: 'upcoming',
    role: '董竹君',
    poster: '/images/works/yulanhuakaijunzailai.jpg',
    year: 2025,
    platform: '腾讯视频',
    description: '待拍',
  },
  {
    id: 'tv-upcoming-2',
    title: '生命树',
    type: 'tv',
    status: 'upcoming',
    role: '白菊',
    poster: '/images/works/shengmingshu.jpg',
    year: 2025,
    platform: '爱奇艺',
    description: '待播',
  },
  {
    id: 'tv-upcoming-3',
    title: '家业',
    type: 'tv',
    status: 'upcoming',
    role: '李祯',
    poster: '/images/works/jiaye.jpg',
    year: 2025,
    platform: '爱奇艺',
    description: '待播',
  },
  {
    id: 'tv-upcoming-4',
    title: '青簪行',
    type: 'tv',
    status: 'upcoming',
    role: '黄梓瑕/杨崇古',
    poster: '/images/works/qingzanxing.jpg',
    year: 2025,
    platform: '腾讯视频',
    description: '待播',
  },

  // 2020-2025
  {
    id: 'tv-2025-1',
    title: '锦绣芳华',
    type: 'tv',
    status: 'aired',
    role: '何惟芳',
    poster: '/images/works/jinxiufanghua.jpg',
    year: 2025,
    platform: '芒果TV',
  },
  {
    id: 'tv-2025-2',
    title: '国色芳华',
    type: 'tv',
    status: 'aired',
    role: '何惟芳',
    poster: '/images/works/guosefanghua.jpg',
    year: 2025,
    platform: '芒果TV',
  },
  {
    id: 'tv-2024-1',
    title: '承欢记',
    type: 'tv',
    status: 'aired',
    role: '麦承欢',
    poster: '/images/works/chenghuanji.jpg',
    year: 2024,
    platform: '腾讯视频',
  },
  {
    id: 'tv-2024-2',
    title: '长相思第二季',
    type: 'tv',
    status: 'aired',
    role: '小夭/玟小六',
    poster: '/images/works/changxiangsi2.jpg',
    year: 2024,
    platform: '腾讯视频',
  },
  {
    id: 'tv-2024-3',
    title: '要久久爱',
    type: 'tv',
    status: 'aired',
    role: '黄瀛子',
    poster: '/images/works/yaojiujiuai.jpg',
    year: 2024,
    platform: '优酷',
  },
  {
    id: 'tv-2023-1',
    title: '长相思第一季',
    type: 'tv',
    status: 'aired',
    role: '小夭/玟小六',
    poster: '/images/works/changxiangsi1.jpg',
    year: 2023,
    platform: '腾讯视频',
  },
  {
    id: 'tv-2022-1',
    title: '沉香如屑',
    type: 'tv',
    status: 'aired',
    role: '颜淡',
    poster: '/images/works/chenxiangruxie.jpg',
    year: 2022,
    platform: '优酷',
  },
  {
    id: 'tv-2022-2',
    title: '余生，请多指教',
    type: 'tv',
    status: 'aired',
    role: '林之校',
    poster: '/images/works/yushengqingduozhijiao.jpg',
    year: 2022,
    platform: '腾讯视频',
  },
  {
    id: 'tv-2021-1',
    title: '女心理师',
    type: 'tv',
    status: 'aired',
    role: '贺顿',
    poster: '/images/works/nvxinlishi.jpg',
    year: 2021,
    platform: '优酷',
  },
  {
    id: 'tv-2021-2',
    title: '我的时代，你的时代',
    type: 'tv',
    status: 'aired',
    role: '佟年',
    poster: '/images/works/wodeshidainideshidai.jpg',
    year: 2021,
    platform: '爱奇艺',
  },
  
  // 2016-2019
  {
    id: 'tv-2019-1',
    title: '我的莫格利男孩',
    type: 'tv',
    status: 'aired',
    role: '凌熙',
    poster: '/images/works/wodemogelinanhai.jpg',
    year: 2019,
    platform: '爱奇艺',
  },
  {
    id: 'tv-2019-2',
    title: '亲爱的，热爱的',
    type: 'tv',
    status: 'aired',
    role: '佟年',
    poster: '/images/works/qinaidereaide.jpg',
    year: 2019,
    platform: '爱奇艺、腾讯视频',
    description: '2019年双台破一言情甜宠剧',
    awards: [
      '2020爱奇艺尖叫之夜「年度剧王」',
      '2019百度沸点「年度电视剧」',
      '2019新浪年度影视综盛典「年度十大剧集之一」',
      '2019腾讯视频星光大赏「年度观众选择剧」',
      '2019微博之夜「微博年度热剧」'
    ]
  },
  {
    id: 'tv-2018-1',
    title: '香蜜沉沉烬如霜',
    type: 'tv',
    status: 'aired',
    role: '锦觅',
    poster: '/images/works/xiangmichenchenjinrushuang.jpg',
    year: 2018,
    platform: '爱奇艺、腾讯视频、优酷',
    description: '2018年卫视年冠古装神话剧',
    awards: [
      '第14届首尔国际电视节「最受欢迎海外电视剧奖」',
      '第2届金鲛奖「2018年度十佳网剧」',
      '2018微博之夜「微博年度热剧」',
      '2018电视剧大赏「年度十大人气剧集」',
      '影视榜样·2018年度总评榜「年度人气剧集」',
      '2018中国文娱指数盛典-艺恩数据「2018年度最具价值剧集」',
      '2018第9届互联网牛耳文娱盛典「“年度现象级电视剧”奖」',
      '第2届金河豚奖「最佳剧集项目」',
      '第3届指尖移动影响力高峰论坛「2018指尖剧集榜最具移动影响力电视剧(网剧)十强」',
      '2018腾讯视频星光盛典「年度十大观众选择剧」',
      '2018中国（深圳）国际电视剧节目交易会「“年度优秀剧目”奖」'
    ]
  },
  {
    id: 'tv-2018-2',
    title: '天乩之白蛇传说',
    type: 'tv',
    status: 'aired',
    role: '白夭夭',
    poster: '/images/works/tianjichuanshuo.jpg',
    year: 2018,
    platform: '暂无',
  },
  {
    id: 'tv-2018-3',
    title: '北京女子图鉴',
    type: 'tv',
    status: 'aired',
    role: '苗苗',
    poster: '/images/works/beijingnvzitujian.jpg',
    year: 2018,
    platform: '优酷',
    description: '客串',
    awards: [
      '第3届金骨朵网络影视盛典年度十大精品网络剧'
    ]
  },
  {
    id: 'tv-2017-1',
    title: '欢乐颂 2',
    type: 'tv',
    status: 'aired',
    role: '邱莹莹',
    poster: '/images/works/huanlesong.jpg',
    year: 2017,
    platform: '爱奇艺、腾讯视频、搜狐、乐视',
    awards: [
      '2017年度脏烟灰缸奖「无烟电视剧奖」'
    ]
  },
  {
    id: 'tv-2017-2',
    title: '龙珠传奇之无间道',
    type: 'tv',
    status: 'aired',
    role: '李易欢',
    poster: '/images/works/longzhuchuanshuo.jpg',
    year: 2017,
    platform: '爱奇艺、腾讯视频、优酷',
  },
  {
    id: 'tv-2016-1',
    title: '青云志2',
    type: 'tv',
    status: 'aired',
    role: '陆雪琪',
    poster: '/images/works/qingyunzhi.jpg',
    year: 2016,
    platform: '腾讯视频',
  },
  {
    id: 'tv-2016-2',
    title: '青云志',
    type: 'tv',
    status: 'aired',
    role: '陆雪琪',
    poster: '/images/works/qingyunzhi.jpg',
    year: 2016,
    platform: '腾讯视频、优酷、芒果TV',
    description: '2017年大IP改编古装玄幻剧',
    awards: [
      '2016腾讯视频星光大赏「电视剧VIP尊贵选择奖」',
      '2016年度最佳游戏电视剧',
      '2016酷云互动年度国民品牌周播剧',
      '入围-第22届华鼎奖「百强名单的前十名电视剧」'
    ]
  },
  {
    id: 'tv-2016-3',
    title: '大嫁风尚',
    type: 'tv',
    status: 'aired',
    role: '夏燃',
    poster: '/images/works/dajiafengshang.jpg',
    year: 2016,
    platform: '腾讯视频',
    awards: [
      '第12届中美电影节“金天使奖”「优秀中国电视剧金天使奖」'
    ]
  },
  {
    id: 'tv-2016-4',
    title: '欢乐颂',
    type: 'tv',
    status: 'aired',
    role: '邱莹莹',
    poster: '/images/works/huanlesong.jpg',
    year: 2016,
    platform: '爱奇艺、腾讯视频、优酷、搜狐、乐视',
    description: '2016年国民爆款现代都市剧',
    awards: [
      '第31届中国电视剧飞天奖「现实题材优秀电视剧大奖」',
      '第7届澳门国际电视节「优秀电视剧奖」',
      '第11届全国电视制片业十佳表彰大会「优秀电视剧」',
      '第22届华鼎奖「中国百强电视剧满意度调查榜前十名」',
      '2017电视剧品质盛典「年度品质榜样剧作」',
      '2016腾讯视频星光大赏「年度最佳电视剧」',
      '2016ELLE风尚大典「年度风尚剧集」',
      '提名-第29届中国电视剧飞天奖「电视剧奖」',
      '提名-第23届上海电视节-白玉兰奖「最佳中国电视剧」'
    ]
  },

  // 2012-2015
  {
    id: 'tv-2015-1',
    title: '灵魂摆渡2',
    type: 'tv',
    status: 'aired',
    role: '苏文秀',
    poster: '/images/works/placeholder.jpg',
    year: 2015,
    platform: '爱奇艺',
  },
  {
    id: 'tv-2015-2',
    title: '大秧歌',
    type: 'tv',
    status: 'aired',
    role: '吴若云',
    poster: '/images/works/dayangge.jpg',
    year: 2015,
    platform: '爱奇艺、腾讯视频、搜狐、芒果TV',
    description: '2015年双台破一年代传奇剧',
    awards: [
      '第11届全国电视制片业十佳表彰大会「电视剧优秀作品奖」',
      '第12届精神文明建设“文艺精品工程”「优秀作品奖」',
      '提名-2016中国电视剧盛典盛典「品质奖」',
      '提名-中国电视剧品质盛典「观众最喜爱电视剧」'
    ]
  },
  {
    id: 'tv-2015-3',
    title: '天生要完美',
    type: 'tv',
    status: 'aired',
    role: '安小慧',
    poster: '/images/works/placeholder.jpg',
    year: 2015,
    platform: '腾讯视频、优酷、乐视、搜狐',
  },
  {
    id: 'tv-2014-1',
    title: '战长沙',
    type: 'tv',
    status: 'aired',
    role: '胡湘湘',
    poster: '/images/works/zhanchangsha.jpg',
    year: 2014,
    platform: '爱奇艺、腾讯视频',
    description: '2014年豆瓣评分第一战争正剧',
  },
  {
    id: 'tv-2013-1',
    title: '花非花雾非雾',
    type: 'tv',
    status: 'aired',
    role: '白梦华',
    poster: '/images/works/placeholder.jpg',
    year: 2013,
    platform: '腾讯视频、优酷、乐视',
  },
  {
    id: 'tv-2013-2',
    title: '老爸回家',
    type: 'tv',
    status: 'aired',
    role: '林然然',
    poster: '/images/works/placeholder.jpg',
    year: 2013,
    platform: '腾讯视频、优酷、芒果TV、哔哩哔哩',
  },
  {
    id: 'tv-2013-3',
    title: '胭脂霸王',
    type: 'tv',
    status: 'aired',
    role: '王雷儿',
    poster: '/images/works/placeholder.jpg',
    year: 2013,
    platform: '西瓜视频、PPTV',
  },
  {
    id: 'tv-2012-1',
    title: '心术',
    type: 'tv',
    status: 'aired',
    role: '张晓蕾',
    poster: '/images/works/placeholder.jpg',
    year: 2012,
    platform: '爱奇艺',
    awards: [
      '第29届中国电视剧飞天奖「长篇电视剧三等奖」',
      '第9届全国电视制片业十佳表彰大会「优秀电视剧」',
      '安徽卫视国剧盛典「年度十佳电视剧第八名」',
      '第4届大学生电视节「最受大学生瞩目现实题材电视剧奖项」'
    ]
  },

  // 2006-2011
  {
    id: 'tv-2011-1',
    title: '幸福来敲门',
    type: 'tv',
    status: 'aired',
    role: '宋征',
    poster: '/images/works/placeholder.jpg',
    year: 2011,
    platform: '搜狐、PPTV',
    awards: [
      '2011春季电视剧互联网盛典「最佳电视剧」',
      '2011春季电视剧互联网盛典「最佳网络收视贡献TOP5」',
      '第28届中国电视剧飞天奖「长篇电视剧二等奖」'
    ]
  },
  {
    id: 'tv-2010-1',
    title: '男生日记',
    type: 'tv',
    status: 'aired',
    role: '冉冬阳',
    poster: '/images/works/placeholder.jpg',
    year: 2010,
    platform: '腾讯视频、优酷、乐视、哔哩哔哩、西瓜视频、PPTV',
  },
  {
    id: 'tv-2009-1',
    title: '女孩冲冲冲',
    type: 'tv',
    status: 'aired',
    role: '孙权',
    poster: '/images/works/placeholder.jpg',
    year: 2009,
    platform: '腾讯视频、优酷、乐视、哔哩哔哩',
  },

  // 2000-2005
  {
    id: 'tv-2005-1',
    title: '家有儿女 2',
    type: 'tv',
    status: 'aired',
    role: '夏雪',
    poster: '/images/works/jiayouernv2.jpg',
    year: 2005,
    platform: '腾讯视频、优酷、央视网',
  },
  {
    id: 'tv-2005-2',
    title: '女生日记',
    type: 'tv',
    status: 'aired',
    role: '冉冬阳',
    poster: '/images/works/placeholder.jpg',
    year: 2005,
    platform: '爱奇艺、腾讯视频、优酷、乐视、西瓜视频',
  },
  {
    id: 'tv-2005-3',
    title: '家有儿女',
    type: 'tv',
    status: 'aired',
    role: '夏雪',
    poster: '/images/works/jiayouernv1.jpg',
    year: 2005,
    platform: '腾讯视频、优酷、央视网',
    awards: [
      '第26届电视剧飞天奖少儿电视剧一等奖',
      '第7届金鹰节中荣获最佳少儿电视剧奖',
      '第10届“五个一工程奖”优秀电视剧奖'
    ]
  },
  {
    id: 'tv-2004-1',
    title: '少年康熙',
    type: 'tv',
    status: 'aired',
    role: '小冰月',
    poster: '/images/works/placeholder.jpg',
    year: 2004,
    platform: '爱奇艺、腾讯视频、乐视',
  },
  {
    id: 'tv-2002-1',
    title: '孝庄秘史',
    type: 'tv',
    status: 'aired',
    role: '小宛如',
    poster: '/images/works/placeholder.jpg',
    year: 2002,
    platform: '优酷',
    awards: [
      '第13届春燕奖「最佳长篇电视剧」',
      '第21届中国电视金鹰奖「优秀作品奖」'
    ]
  },

  // Movies
  {
    id: 'mv-2023-1',
    title: '猎毒',
    type: 'movie',
    status: 'upcoming',
    role: '骆佳',
    poster: '/images/works/liedu.jpg',
    year: 2023, // Updated based on list context, though listed as 2022 in text, usually use latest
    platform: '待播',
  },
  {
    id: 'mv-2023-2',
    title: '热辣滚烫',
    type: 'movie',
    status: 'aired',
    role: '豆豆', // Updated based on public info as role was "待官宣" in source but known
    poster: '/images/works/relaguntang.jpg',
    year: 2023,
    platform: '待播',
  },
  {
    id: 'mv-2020-1',
    title: '赤狐书生',
    type: 'movie',
    status: 'aired',
    role: '映无邪',
    poster: '/images/works/placeholder.jpg',
    year: 2020,
    platform: '腾讯视频、优酷',
    description: '友情出演',
  },
  {
    id: 'mv-2020-2',
    title: '我和我的家乡',
    type: 'movie',
    status: 'aired',
    role: '姜紫丫',
    poster: '/images/works/wohewodejiaxiang.jpg',
    year: 2020,
    platform: '芒果TV',
  },
  {
    id: 'mv-2019-1',
    title: '沉默的证人',
    type: 'movie',
    status: 'aired',
    role: '乔琳',
    poster: '/images/works/chenmodezhengren.jpg',
    year: 2019,
    platform: '爱奇艺、腾讯视频、优酷、芒果TV、乐视',
  },
  {
    id: 'mv-2019-2',
    title: '烈火英雄',
    type: 'movie',
    status: 'aired',
    role: '王璐',
    poster: '/images/works/liehuoyingxiong.jpg',
    year: 2019,
    platform: '爱奇艺、腾讯视频、优酷、芒果TV、乐视、电影网',
    awards: [
      '第3届全国中小学生电影周「我最喜爱的优秀影片」',
      '第32届东京国际电影节金鹤奖「最佳作品」',
      '提名-第11届澳门国际电影节「最佳影片奖」'
    ]
  },
  {
    id: 'mv-2017-1',
    title: '一纸婚约',
    type: 'movie',
    status: 'aired',
    role: '琳琳',
    poster: '/images/works/placeholder.jpg',
    year: 2017,
    platform: '优酷',
    awards: [
      '第50届休斯顿国际电影节「评委会特别奖」'
    ]
  },
  {
    id: 'mv-2016-1',
    title: '在世界中心呼唤爱',
    type: 'movie',
    status: 'aired',
    role: '夏叶',
    poster: '/images/works/placeholder.jpg',
    year: 2016,
    platform: '爱奇艺、腾讯视频、优酷、芒果TV、电影网',
  },
  {
    id: 'mv-2016-2',
    title: '洛杉矶捣蛋计划',
    type: 'movie',
    status: 'aired',
    role: '王妮娜',
    poster: '/images/works/placeholder.jpg',
    year: 2016,
    platform: '爱奇艺、腾讯视频、电影网',
  },
  {
    id: 'mv-2015-1',
    title: '时间都去哪了',
    type: 'movie',
    status: 'aired',
    role: '林雨桐',
    poster: '/images/works/placeholder.jpg',
    year: 2015,
    platform: '爱奇艺、腾讯视频、优酷、乐视',
  },
  {
    id: 'mv-2014-1',
    title: '斗茶',
    type: 'movie',
    status: 'aired',
    role: '谢小香',
    poster: '/images/works/placeholder.jpg',
    year: 2014,
    platform: '腾讯视频、优酷、芒果TV',
  },
  {
    id: 'mv-2012-1',
    title: '守株人',
    type: 'movie',
    status: 'aired',
    role: '王佳佳',
    poster: '/images/works/placeholder.jpg',
    year: 2012,
    platform: '腾讯视频、电影网',
  },
  {
    id: 'mv-2010-1',
    title: '三班五班',
    type: 'movie',
    status: 'aired',
    role: '冉冬阳',
    poster: '/images/works/placeholder.jpg',
    year: 2010,
    platform: '电影网',
  },
  {
    id: 'mv-2009-1',
    title: '男生女生',
    type: 'movie',
    status: 'aired',
    role: '冉冬阳',
    poster: '/images/works/placeholder.jpg',
    year: 2009,
    platform: '电影网',
  },
  {
    id: 'mv-2004-1',
    title: '女生日记',
    type: 'movie',
    status: 'aired',
    role: '冉冬阳',
    poster: '/images/works/placeholder.jpg',
    year: 2004,
    platform: '电影网',
  },

  // Music - OST
  {
    id: 'music-ost-1',
    title: '相见相思',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/changxiangsi1.jpg',
    year: 2023,
    platform: 'QQ音乐、酷狗音乐、酷我音乐',
    description: '电视剧《长相思》相思曲',
  },
  {
    id: 'music-ost-2',
    title: '偏爱人间烟火',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/changxiangsi1.jpg',
    year: 2023,
    platform: 'QQ音乐、酷狗音乐、酷我音乐',
    description: '电视剧《长相思》推广曲 (合唱)',
  },
  {
    id: 'music-ost-3',
    title: '高高山上一根藤',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/changxiangsi1.jpg',
    year: 2023,
    platform: 'QQ音乐、酷狗音乐、酷我音乐',
    description: '电视剧《长相思》童谣',
  },
  {
    id: 'music-ost-4',
    title: '望辰',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/chenxiangruxie.jpg',
    year: 2022,
    platform: 'QQ音乐、酷狗音乐、酷我音乐、咪咕音乐',
    description: '电视剧《沉香如屑·沉香重华》颜淡主题曲',
  },
  {
    id: 'music-ost-5',
    title: '花房咖啡厅',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/nvxinlishi.jpg',
    year: 2021,
    platform: 'QQ音乐、酷狗音乐、酷我音乐',
    description: '电视剧《女心理师》片尾曲',
  },
  {
    id: 'music-ost-6',
    title: '心理大师',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/nvxinlishi.jpg',
    year: 2021,
    platform: 'QQ音乐、酷狗音乐、酷我音乐',
    description: '电视剧《女心理师》片头曲 (合唱)',
  },
  {
    id: 'music-ost-7',
    title: '一个人喜欢一个人',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/yushengqingduozhijiao.jpg',
    year: 2022,
    platform: 'QQ音乐、酷狗音乐、酷我音乐',
    description: '电视剧《余生，请多指教》片尾曲',
  },
  {
    id: 'music-ost-8',
    title: '余生请多指教',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/yushengqingduozhijiao.jpg',
    year: 2022,
    platform: 'QQ音乐、酷狗音乐、酷我音乐',
    description: '《余生，请多指教》主题曲',
  },
  {
    id: 'music-ost-9',
    title: '牛奶面包',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/qinaidereaide.jpg',
    year: 2019,
    platform: '网易云音乐',
    description: '电视剧《亲爱的，热爱的》片尾曲',
  },
  {
    id: 'music-ost-10',
    title: '有风的夜晚',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/wodemogelinanhai.jpg',
    year: 2019,
    platform: '各大音乐平台',
    description: '电视剧《我的莫格利男孩》片尾曲',
  },
  {
    id: 'music-ost-11',
    title: '打破沉默',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/chenmodezhengren.jpg',
    year: 2019,
    platform: '各大音乐平台',
    description: '电影《沉默的证人》主题曲',
  },
  {
    id: 'music-ost-12',
    title: '影院安全消防指南',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/liehuoyingxiong.jpg',
    year: 2019,
    platform: 'MV视频',
    description: '电影《烈火英雄》宣传曲',
  },
  {
    id: 'music-ost-13',
    title: '中餐厅',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2019,
    platform: '网易云音乐',
    description: '综艺《中餐厅》主题曲 (合唱)',
  },
  {
    id: 'music-ost-14',
    title: '情霜',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/xiangmichenchenjinrushuang.jpg',
    year: 2018,
    platform: '网易云音乐',
    description: '电视剧《香蜜沉沉烬如霜》插曲',
  },
  {
    id: 'music-ost-15',
    title: '天地无霜',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/xiangmichenchenjinrushuang.jpg',
    year: 2018,
    platform: '网易云音乐',
    description: '电视剧《香蜜沉沉烬如霜》插曲 (合唱)',
  },
  {
    id: 'music-ost-16',
    title: '几生欢',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/tianjichuanshuo.jpg',
    year: 2018,
    platform: 'QQ音乐',
    description: '电视剧《天乩之白蛇传说》插曲',
  },
  {
    id: 'music-ost-17',
    title: '功夫瑜伽',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2017,
    platform: 'QQ音乐',
    description: '电影《功夫瑜伽》主题曲 (合唱)',
  },
  {
    id: 'music-ost-18',
    title: '若只如初见',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/qingyunzhi.jpg',
    year: 2016,
    platform: 'QQ音乐',
    description: '电视剧《青云志》插曲',
  },
  {
    id: 'music-ost-19',
    title: '蚯蚓',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/huanlesong.jpg',
    year: 2016,
    platform: '网易云音乐、QQ音乐',
    description: '电视剧《欢乐颂》插曲',
  },
  {
    id: 'music-ost-20',
    title: '开得比花香',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/huanlesong.jpg',
    year: 2016,
    platform: '网易云音乐',
    description: '电视剧《欢乐颂》插曲',
  },
  {
    id: 'music-ost-21',
    title: '总有幸福在等你',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/huanlesong.jpg',
    year: 2016,
    platform: '网易云音乐',
    description: '电视剧《欢乐颂》主题曲 (合唱)',
  },
  {
    id: 'music-ost-22',
    title: '我们',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/huanlesong.jpg',
    year: 2016,
    platform: '网易云音乐',
    description: '电视剧《欢乐颂》片尾曲 (合唱)',
  },
  {
    id: 'music-ost-23',
    title: '我会记得你',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/zhanchangsha.jpg',
    year: 2014,
    platform: '网易云音乐',
    description: '电视剧《战长沙》片尾曲 (合唱)',
  },
  {
    id: 'music-ost-24',
    title: '胭脂花开',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2013,
    platform: 'QQ音乐',
    description: '电视剧《胭脂霸王》片尾曲',
  },
  {
    id: 'music-ost-25',
    title: '寂静的瓦砾',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2012,
    platform: 'QQ音乐',
    description: '电影《守株人》主题曲',
  },
  {
    id: 'music-ost-26',
    title: '每天长大一点点',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2009,
    platform: 'QQ音乐',
    description: '儿童魔幻剧《不想长大》主题曲',
  },
  {
    id: 'music-ost-27',
    title: '牵手五环',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2008,
    platform: 'QQ音乐',
    description: '为北京2008年奥运会创作',
  },
  {
    id: 'music-ost-28',
    title: '中国',
    type: 'music',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2019,
    platform: 'QQ音乐',
    description: '百位歌手倾情献唱《中国》贺岁版MV',
  },

  // Music - Covers
  {
    id: 'music-cover-1',
    title: '樱花草',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐、酷狗音乐',
    description: 'Cover Sweety',
  },
  {
    id: 'music-cover-2',
    title: '我不是黄蓉',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐',
    description: 'Cover 王蓉',
  },
  {
    id: 'music-cover-3',
    title: '私奔',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: '网易云音乐',
    description: 'Cover 曾轶可',
  },
  {
    id: 'music-cover-4',
    title: '告白气球',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐',
    description: 'Cover 周杰伦 (合唱)',
  },
  {
    id: 'music-cover-5',
    title: '小毛驴',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐',
    description: 'Cover 林重冏',
  },
  {
    id: 'music-cover-6',
    title: '最天使',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: '网易云音乐',
    description: 'Cover 曾轶可',
  },
  {
    id: 'music-cover-7',
    title: '白色秋天',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: '网易云音乐',
    description: 'Cover 曾轶可',
  },
  {
    id: 'music-cover-8',
    title: '达尔文',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: '网易云音乐',
    description: 'Cover 蔡健雅',
  },
  {
    id: 'music-cover-9',
    title: '恰似你的温柔',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐',
    description: 'Cover 邓丽君',
  },
  {
    id: 'music-cover-10',
    title: '雪人',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: '网易云音乐',
    description: 'Cover 范晓萱',
  },
  {
    id: 'music-cover-11',
    title: '一席幽梦',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: '网易云音乐',
    description: 'Cover 卓依婷',
  },
  {
    id: 'music-cover-12',
    title: '小邋遢',
    type: 'music',
    status: 'aired',
    role: '翻唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐',
    description: 'Cover 曹蕾',
  },

  // Music - Album
  {
    id: 'music-album-1',
    title: '家有小雪',
    type: 'music',
    status: 'aired',
    role: '歌手',
    poster: '/images/works/jiayouernv1.jpg',
    year: 2008,
    platform: 'QQ音乐',
    description: '首张个人EP (收录: 留夏, 加油！小乖, 阳光男孩阳光女孩, 娃娃脸, 小雪, 快乐无极限)',
  },

  // Short - Stage & Live
  {
    id: 'short-stage-1',
    title: '花开种花家',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐、酷狗音乐',
    description: '2023央视春晚现场Live',
  },
  {
    id: 'short-stage-2',
    title: '粉色海洋',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐、酷狗音乐',
    description: '2022-2023湖南卫视跨年演唱会Live',
  },
  {
    id: 'short-stage-3',
    title: '温蒂公主的侍卫',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2022,
    platform: '酷我音乐、酷狗音乐',
    description: '2021-2022湖南卫视跨年演唱会Live',
  },
  {
    id: 'short-stage-4',
    title: '不染+一个人喜欢一个人...',
    titleEn: 'Song Medley',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2021,
    platform: 'QQ音乐、酷狗音乐',
    description: '2020-2021东方卫视跨年晚会 (不染/一个人喜欢一个人/牛奶面包/我们)',
  },
  {
    id: 'short-stage-5',
    title: '山水画卷',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2021,
    platform: '视频',
    description: '2021年央视五四晚会',
  },
  {
    id: 'short-stage-6',
    title: '一个人喜欢一个人',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/yushengqingduozhijiao.jpg',
    year: 2020,
    platform: 'QQ音乐 (星光大赏Live)',
    description: '腾讯视频星光大赏现场版',
  },
  {
    id: 'short-stage-7',
    title: '余生，请多指教',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/works/yushengqingduozhijiao.jpg',
    year: 2020,
    platform: 'QQ音乐 (星光大赏Live)',
    description: '腾讯视频星光大赏现场版',
  },
  {
    id: 'short-stage-8',
    title: '向上的光',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: 'QQ音乐',
    description: '央视国庆晚会',
  },
  {
    id: 'short-stage-9',
    title: '记住这个画面',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2022,
    platform: 'QQ音乐',
    description: '第35届金鸡百花电影节',
  },
  {
    id: 'short-stage-10',
    title: '你要相信这不是最后一天',
    type: 'short',
    status: 'aired',
    role: '献声',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '网易云音乐',
    description: '抗疫公益歌曲',
  },
  {
    id: 'short-stage-11',
    title: '天使的身影',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '视频',
    description: '抗疫公益歌曲',
  },
  {
    id: 'short-stage-12',
    title: '再次相约二十年',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: 'QQ音乐',
    description: '2020央视春晚现场版',
  },
  {
    id: 'short-stage-13',
    title: '北京我的爱',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '网易云音乐',
    description: '2020北京电视台春晚现场版',
  },
  {
    id: 'short-stage-14',
    title: '青春畅想',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '视频',
    description: '百花迎春中国文学艺术界2020春节大联欢',
  },
  {
    id: 'short-stage-15',
    title: '梦想',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '视频',
    description: '中国大学生电视节主题曲',
  },
  {
    id: 'short-stage-16',
    title: '今天是你的生日',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2019,
    platform: '视频',
    description: '祝福祖国快闪活动',
  },
  {
    id: 'short-stage-17',
    title: '儿时',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2019,
    platform: '视频',
    description: '2019北京电视台春晚现场版',
  },
  {
    id: 'short-stage-18',
    title: '有可能的夜晚',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '网易云音乐',
    description: '2020湖南卫视跨年演唱会现场版',
  },
  {
    id: 'short-stage-19',
    title: '不染',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/works/xiangmichenchenjinrushuang.jpg',
    year: 2019,
    platform: '网易云音乐',
    description: '2019湖南卫视跨年演唱会现场版',
  },
  {
    id: 'short-stage-20',
    title: '水星记',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2019,
    platform: 'QQ音乐',
    description: '2019芭莎慈善夜现场版',
  },
  {
    id: 'short-stage-21',
    title: '小梦想大梦想',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2019,
    platform: 'QQ音乐',
    description: '2019央视五四晚会/元旦晚会',
  },
  {
    id: 'short-stage-22',
    title: '强国一代有我在',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2019,
    platform: 'QQ音乐',
    description: '2019湖南五四晚会现场版',
  },
  {
    id: 'short-stage-23',
    title: '赞赞新时代',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2018,
    platform: 'QQ音乐',
    description: '庆祝建党97周年晚会',
  },
  {
    id: 'short-stage-24',
    title: '用尽我的一切奔向你',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2018,
    platform: 'QQ音乐',
    description: '第12届中国金鹰电视艺术节颁奖晚会',
  },
  {
    id: 'short-stage-25',
    title: '美丽中国年',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2017,
    platform: '视频',
    description: '2017央视春晚',
  },
  {
    id: 'short-stage-26',
    title: '寻人启事',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2017,
    platform: '视频',
    description: '2017魏晨演唱会嘉宾',
  },
  {
    id: 'short-stage-27',
    title: '我们的小世界',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2017,
    platform: '视频',
    description: '2017魏晨演唱会嘉宾',
  },
  {
    id: 'short-stage-28',
    title: '欢乐颂开播盛典',
    titleEn: 'Ode to Joy Medley',
    type: 'short',
    status: 'aired',
    role: '合唱/独唱',
    poster: '/images/works/huanlesong.jpg',
    year: 2016,
    platform: '视频',
    description: '收录: 蚯蚓, 开的比花香, 我们, 总有幸福在等你, 小酒窝',
  },
  {
    id: 'short-stage-29',
    title: '未来已来',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2017,
    platform: 'QQ音乐',
    description: '推广曲',
  },

  // Short - Other
  {
    id: 'short-other-1',
    title: '我的祖国',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/works/wohewodejiaxiang.jpg',
    year: 2020,
    platform: 'QQ音乐、酷狗音乐',
    description: '电影《我和我的家乡》推广曲',
  },
  {
    id: 'short-other-2',
    title: '自带清风',
    type: 'short',
    status: 'aired',
    role: '合唱',
    poster: '/images/brands/placeholder.svg',
    year: 2021,
    platform: 'QQ音乐、酷狗音乐',
    description: '清风品牌推广曲',
  },
  {
    id: 'short-other-3',
    title: '生如夏花',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2023,
    platform: 'QQ音乐',
    description: '音频',
  },
  {
    id: 'short-other-4',
    title: '仰望',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '酷我音乐',
    description: '青年演员致敬平凡英雄',
  },
  {
    id: 'short-other-5',
    title: '逆行者',
    type: 'short',
    status: 'aired',
    role: '演唱',
    poster: '/images/brands/placeholder.svg',
    year: 2020,
    platform: '视频',
    description: '美好中国云晚会致敬消防英雄',
  },

  // Variety Shows
  // 2025
  {
    id: 'variety-2025-1',
    title: '你好星期六',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2025,
    platform: '芒果TV',
    description: '20250119, 20250125, 20250126',
  },

  // 2024
  {
    id: 'variety-2024-1',
    title: '你好星期六',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2024,
    platform: '芒果TV',
    description: '20240120 - 宣传《要久久爱》',
  },

  // 2023
  {
    id: 'variety-2023-1',
    title: '我们的美好生活',
    type: 'variety',
    status: 'aired',
    role: '常驻嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2023,
    platform: '芒果TV',
    description: '第1-2期, 加更版, 超前营业',
  },
  {
    id: 'variety-2023-2',
    title: '你好星期六',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2023,
    platform: '芒果TV',
    description: '20230708 - 宣传《长相思1》, 20230802 - 加更, 20230819 - 加更',
  },

  // 2022
  {
    id: 'variety-2022-1',
    title: '你好星期六',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2022,
    platform: '芒果TV',
    description: '20220723, 20220730',
  },

  // 2021
  {
    id: 'variety-2021-1',
    title: '萌探探探案',
    type: 'variety',
    status: 'aired',
    role: '常驻嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2021,
    platform: '爱奇艺',
    description: '第1-7期, 第10期',
  },
  {
    id: 'variety-2021-2',
    title: '向往的生活第五季',
    type: 'variety',
    status: 'aired',
    role: '飞行嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2021,
    platform: '芒果TV',
    description: '第4-6期',
  },

  // 2020
  {
    id: 'variety-2020-1',
    title: '国家宝藏第三季',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2020,
    platform: '腾讯、优酷、爱奇艺、B站',
    description: '第3期 -《文成公主》',
  },
  {
    id: 'variety-2020-2',
    title: '听见她说',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2020,
    platform: '腾讯视频',
    description: '第2期 -《许愿》',
  },

  // 2019
  {
    id: 'variety-2019-1',
    title: '中餐厅 第三季',
    type: 'variety',
    status: 'aired',
    role: '常驻嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2019,
    platform: '腾讯、芒果TV',
    description: '全12期 + 先导片',
  },
  {
    id: 'variety-2019-2',
    title: '新闻当事人',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2019,
    platform: '腾讯、芒果TV',
    description: '20190817 - 杨紫 进击女孩',
  },
  {
    id: 'variety-2019-3',
    title: '甜蜜的任务',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2019,
    platform: '芒果TV',
    description: '第28期',
  },
  {
    id: 'variety-2019-4',
    title: '拜托了冰箱 第五季',
    type: 'variety',
    status: 'aired',
    role: '飞行嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2019,
    platform: '腾讯视频',
    description: '第9-10期',
  },

  // 2018
  {
    id: 'variety-2018-1',
    title: '亲爱的客栈 第二季',
    type: 'variety',
    status: 'aired',
    role: '飞行嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2018,
    platform: '腾讯、芒果TV',
    description: '第6-7期',
  },
  {
    id: 'variety-2018-2',
    title: '高能少年团 第二季',
    type: 'variety',
    status: 'aired',
    role: '常驻嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2018,
    platform: '爱奇艺、腾讯、优酷、中国蓝TV',
    description: '共11期',
  },
  {
    id: 'variety-2018-3',
    title: '一封家书',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2018,
    platform: '腾讯视频',
    description: '20180303 - “你们永远是我的超人”',
  },

  // 2017
  {
    id: 'variety-2017-1',
    title: '星空演讲',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2017,
    platform: '腾讯视频',
    description: '20171114',
  },
  {
    id: 'variety-2017-2',
    title: '亲爱的客栈 第一季',
    type: 'variety',
    status: 'aired',
    role: '飞行嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2017,
    platform: '腾讯、芒果TV',
    description: '第5-7期',
  },
  {
    id: 'variety-2017-3',
    title: '快乐大本营',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2017,
    platform: '芒果TV',
    description: '20170527 - 宣传《龙珠传奇》',
  },
  {
    id: 'variety-2017-4',
    title: '高能少年团 第一季',
    type: 'variety',
    status: 'aired',
    role: '飞行嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2017,
    platform: '爱奇艺、腾讯、优酷、乐视、中国蓝TV',
    description: '第6期',
  },

  // 2016
  {
    id: 'variety-2016-1',
    title: '金星秀',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2016,
    platform: '优酷',
    description: '20161102 - “奇葩养生”那些事',
  },
  {
    id: 'variety-2016-2',
    title: '新闻当事人',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2016,
    platform: '腾讯、芒果TV',
    description: '20160918 - 杨紫 邻家有女初长成',
  },
  {
    id: 'variety-2016-3',
    title: '快乐大本营',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2016,
    platform: '芒果TV',
    description: '20160827 - 宣传《青云志》, 20160625 - 宣传《欢乐颂》',
  },
  {
    id: 'variety-2016-4',
    title: '妈妈的牵挂',
    type: 'variety',
    status: 'aired',
    role: '前半程常驻嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2016,
    platform: '芒果TV',
    description: '共8期',
  },

  // 2015
  {
    id: 'variety-2015-1',
    title: '非常静距离',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2015,
    platform: '爱奇艺、腾讯',
    description: '20150708',
  },
  {
    id: 'variety-2015-2',
    title: '文字英雄',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2015,
    platform: '腾讯、乐视',
    description: '20150612 - “三国”文学主题',
  },
  {
    id: 'variety-2015-3',
    title: '花样姐姐 第一季',
    type: 'variety',
    status: 'aired',
    role: '后半程常驻嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2015,
    platform: '爱奇艺、腾讯',
    description: '第6-12期',
  },
  {
    id: 'variety-2015-4',
    title: '疯狂的麦咭 第二季',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2015,
    platform: '芒果TV',
    description: '第9期',
  },

  // 2014
  {
    id: 'variety-2014-1',
    title: '谢天谢地你来啦',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2014,
    platform: 'CCTV',
    description: '20141121',
  },
  {
    id: 'variety-2014-2',
    title: '花样年华 第二季',
    type: 'variety',
    status: 'aired',
    role: '常驻嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2014,
    platform: '哔哩哔哩、搜狐、PPTV',
    description: '全12期',
  },
  {
    id: 'variety-2014-3',
    title: '百变大咖秀 第五季',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2014,
    platform: '芒果TV',
    description: '20140327',
  },
  {
    id: 'variety-2014-4',
    title: '我的校友是明星',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2014,
    platform: '网络',
    description: '20140225',
  },
  {
    id: 'variety-2014-5',
    title: '过年七天乐',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2014,
    platform: 'CCTV',
    description: '20140131',
  },

  // 2013
  {
    id: 'variety-2013-1',
    title: '光荣绽放',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2013,
    platform: '爱奇艺、腾讯',
    description: '20130924 - 北京丫头杨紫',
  },
  {
    id: 'variety-2013-2',
    title: 'CCTV艺术人生',
    type: 'variety',
    status: 'aired',
    role: '嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2013,
    platform: 'CCTV',
    description: '20130808 - 《致青春》系列',
  },
  {
    id: 'variety-2013-3',
    title: '快乐大本营',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2013,
    platform: '芒果TV',
    description: '20130727 - 宣传《花非花雾非雾》',
  },

  // 2012
  {
    id: 'variety-2012-1',
    title: '年代秀 第七季',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2012,
    platform: '搜狐视频',
    description: '第9期',
  },

  // 2008
  {
    id: 'variety-2008-1',
    title: '天天向上',
    type: 'variety',
    status: 'aired',
    role: '节目嘉宾',
    poster: '/images/works/placeholder.jpg',
    year: 2008,
    platform: '芒果TV',
    description: '20080919 - 武林外传PK家有儿女',
  }
];
export const schedules: Schedule[] = [
  {
    id: '1',
    date: '2024-12-05',
    city: '北京',
    type: 'brand',
    title: '某品牌活动',
    description: '品牌代言活动',
  },
  {
    id: '2',
    date: '2024-12-15',
    city: '上海',
    type: 'variety',
    title: '综艺录制',
  },
  {
    id: '3',
    date: '2024-11-20',
    city: '杭州',
    type: 'event',
    title: '电视节活动',
  },
];

export const brands: Brand[] = [
  // Luxury
  {
    id: 'luxury-1',
    name: 'Valentino',
    nameEn: 'Valentino',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/valentino.jpg',
    title: '品牌代言人',
    category: 'luxury',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023-11',
  },
  {
    id: 'luxury-2',
    name: 'Prada',
    nameEn: 'Prada',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/prada.jpg',
    title: '彩妆及香水品牌代言人',
    category: 'luxury',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  {
    id: 'luxury-3',
    name: 'APM Monaco',
    nameEn: 'APM Monaco',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/apm.jpg',
    title: '全球品牌代言人',
    category: 'luxury',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  
  // Beauty
  {
    id: 'beauty-1',
    name: '丸美',
    nameEn: 'MARUBI',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/marubi.jpg',
    title: '首位全球品牌代言人',
    category: 'beauty',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  {
    id: 'beauty-2',
    name: '淘淘氧棉',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/marubi.jpg',
    title: '首位全球代言人',
    category: 'beauty',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  {
    id: 'beauty-3',
    name: '谷雨',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/marubi.jpg',
    title: '全球防晒代言人 / 全线代言人',
    category: 'beauty',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  {
    id: 'beauty-4',
    name: '养元青',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/marubi.jpg',
    title: '品牌代言人',
    category: 'beauty',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },

  // Food
  {
    id: 'food-1',
    name: '正官庄',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/food.jpg',
    title: '品牌代言人',
    category: 'food',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  {
    id: 'food-2',
    name: '蒙牛纯甄',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/food.jpg',
    title: '全球代言人',
    category: 'food',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  {
    id: 'food-3',
    name: '蒙牛悠瑞',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/food.jpg',
    title: '全球代言人',
    category: 'food',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },
  {
    id: 'food-4',
    name: '果子熟了无糖茶',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/food.jpg',
    title: '全球品牌代言人',
    category: 'food',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },

  // Fashion
  {
    id: 'fashion-1',
    name: '暴龙眼镜',
    nameEn: 'Bolon',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/glasses.jpg',
    title: '全球代言人 / 中国棒球文化推广大使',
    category: 'fashion',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },

  // Auto
  {
    id: 'auto-1',
    name: '奇瑞汽车',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/car.jpg',
    title: '全球代言人',
    category: 'auto',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  },

  // Lifestyle
  {
    id: 'lifestyle-1',
    name: '抖音生活服务',
    logo: '/images/brands/placeholder.svg',
    image: '/images/brands/lifestyle.jpg',
    title: '心动榜代言人',
    category: 'lifestyle',
    status: 'active',
    level: 'spokesperson',
    startDate: '2023',
  }
];

export const magazines: Magazine[] = [
  {
    id: '1',
    name: 'ELLE',
    nameEn: 'ELLE',
    coverImage: '/images/magazines/elle.jpg',
    issue: '2023年12月刊',
    date: '2023-12',
  },
  {
    id: '2',
    name: 'Vogue',
    nameEn: 'Vogue',
    coverImage: '/images/magazines/vogue.jpg',
    issue: '2023年10月刊',
    date: '2023-10',
  },
  {
    id: '3',
    name: '时尚芭莎',
    nameEn: "Harper's BAZAAR",
    coverImage: '/images/magazines/bazaar.jpg',
    issue: '2023年9月刊',
    date: '2023-09',
  },
];

export const awards: Award[] = [
  {
    id: '1',
    name: '年度最具影响力女演员',
    ceremony: '中国电视剧品质盛典',
    category: '影视类',
    year: 2023,
    work: '长相思',
    type: 'film',
    status: 'winner'
  },
  {
    id: '2',
    name: '年度最受欢迎女演员',
    ceremony: '腾讯视频星光大赏',
    category: '影视类',
    year: 2023,
    type: 'film',
    status: 'winner'
  },
  {
    id: '3',
    name: '年度商业价值艺人',
    ceremony: '中国品牌营销盛典',
    category: '商业类',
    year: 2023,
    type: 'commercial',
    status: 'winner'
  },
  {
    id: '4',
    name: '优秀青年演员',
    ceremony: '中国电视金鹰奖',
    category: '影视类',
    year: 2022,
    work: '沉香如屑',
    type: 'film',
    status: 'winner'
  },
  // 2018
  {
    id: 'award-2018-1',
    name: '年度价值艺人',
    ceremony: '价值中国·2018ZAKER影响力指数榜魅力文娱榜',
    category: '商业类',
    year: 2018,
    type: 'commercial',
    status: 'winner'
  },
  {
    id: 'award-2018-2',
    name: '年度荧幕艺人',
    ceremony: '2018百度百科',
    category: '综合类',
    year: 2018,
    type: 'official',
    status: 'winner'
  },
  {
    id: 'award-2018-3',
    name: '年度最受关注明星',
    ceremony: '2018今日头条年度盛典',
    category: '综合类',
    year: 2018,
    type: 'official',
    status: 'winner'
  },
  {
    id: 'award-2018-4',
    name: '中国最具商业价值明星榜第27名',
    ceremony: '2018第一财经周刊',
    category: '商业类',
    year: 2018,
    type: 'commercial',
    status: 'winner'
  },
  {
    id: 'award-2018-5',
    name: '年度国剧女明星',
    ceremony: '2018搜狐时尚盛典',
    category: '影视类',
    year: 2018,
    type: 'film',
    status: 'nomination'
  },
  {
    id: 'award-2018-6',
    name: '年度人气女明星',
    ceremony: '2018搜狐时尚盛典',
    category: '综合类',
    year: 2018,
    type: 'official',
    status: 'winner'
  },
  {
    id: 'award-2018-7',
    name: '年度人气电视剧女演员',
    ceremony: '2018腾讯视频星光盛典',
    category: '影视类',
    year: 2018,
    type: 'film',
    status: 'winner'
  },
  {
    id: 'award-2018-8',
    name: '中国古代题材电视剧最佳女演员奖',
    ceremony: '第24届华鼎奖',
    category: '影视类',
    year: 2018,
    type: 'film',
    status: 'nomination'
  },
  {
    id: 'award-2018-9',
    name: '观众喜爱的女演员奖',
    ceremony: '第29届中国电视金鹰奖',
    category: '影视类',
    year: 2018,
    type: 'film',
    status: 'nomination'
  },
  {
    id: 'award-2018-10',
    name: '最具人气女演员',
    ceremony: '第12届中国金鹰电视艺术节',
    category: '影视类',
    year: 2018,
    type: 'film',
    status: 'nomination'
  },
  {
    id: 'award-2018-11',
    name: 'UNDER30行业精英代表',
    ceremony: '2018福布斯中国',
    category: '商业类',
    year: 2018,
    type: 'commercial',
    status: 'winner'
  },
  {
    id: 'award-2018-12',
    name: '年度人气艺人',
    ceremony: '2017微博之夜',
    category: '综合类',
    year: 2018,
    type: 'official',
    status: 'winner'
  },
  // 2017
  {
    id: 'award-2017-1',
    name: '中国最具商业价值明星榜第30名',
    ceremony: '2017第一财经周刊',
    category: '商业类',
    year: 2017,
    type: 'commercial',
    status: 'winner'
  },
  {
    id: 'award-2017-2',
    name: '年度突破艺人',
    ceremony: '2017微博电视影响力盛典',
    category: '影视类',
    year: 2017,
    type: 'film',
    status: 'winner'
  },
  {
    id: 'award-2017-3',
    name: '福布斯中国名人榜第73名',
    ceremony: '2017福布斯中国名人榜',
    category: '商业类',
    year: 2017,
    type: 'commercial',
    status: 'winner'
  },
  {
    id: 'award-2017-4',
    name: '最佳女配角奖',
    ceremony: '第23届上海电视节白玉兰奖',
    category: '影视类',
    year: 2017,
    type: 'film',
    status: 'nomination'
  },
  {
    id: 'award-2017-5',
    name: '中国古装题材电视剧最佳女演员奖',
    ceremony: '第22届华鼎奖',
    category: '影视类',
    year: 2017,
    type: 'film',
    status: 'nomination'
  },
  {
    id: 'award-2017-6',
    name: '年度品质组合(欢乐颂五美)',
    ceremony: '2017中国电视剧品质盛典',
    category: '影视类',
    year: 2017,
    type: 'film',
    status: 'winner'
  },
  {
    id: 'award-2017-7',
    name: '年度人气艺人',
    ceremony: '2016微博之夜',
    category: '综合类',
    year: 2017,
    type: 'official',
    status: 'winner'
  },
  // 2016
  {
    id: 'award-2016-1',
    name: '年度飞跃女演员(最具青春号召力演员)',
    ceremony: '2016国剧盛典',
    category: '影视类',
    year: 2016,
    type: 'film',
    status: 'winner'
  },
  {
    id: 'award-2016-2',
    name: '2017中国90后10大影响力人物第4名',
    ceremony: '2017中国90后10大影响力人物',
    category: '综合类',
    year: 2016,
    type: 'official',
    status: 'winner'
  },
  {
    id: 'award-2016-3',
    name: '百度娱乐年度人物',
    ceremony: '2016百度明星感恩季',
    category: '综合类',
    year: 2016,
    type: 'official',
    status: 'winner'
  },
  {
    id: 'award-2016-4',
    name: '“90后四小花旦”之一',
    ceremony: '2016南都娱乐周刊',
    category: '综合类',
    year: 2016,
    type: 'official',
    status: 'winner'
  },
  // 2013
  {
    id: 'award-2013-1',
    name: '年度最具广告代言价值明星',
    ceremony: '2013品牌贡献榜·影响中国',
    category: '商业类',
    year: 2013,
    type: 'commercial',
    status: 'winner'
  },
  {
    id: 'award-2013-2',
    name: '新人奖',
    ceremony: '第14届中国电影表演艺术学会金凤凰奖',
    category: '影视类',
    year: 2013,
    type: 'film',
    status: 'winner'
  },
  // 2012
  {
    id: 'award-2012-1',
    name: '最佳女配角奖',
    ceremony: '2012第2届搜狐视频电视剧盛典',
    category: '影视类',
    year: 2012,
    type: 'film',
    status: 'nomination'
  },
  {
    id: 'award-2012-2',
    name: '华鼎中国新锐演员公众形象满意度调查排行榜第83名',
    ceremony: '2012华鼎奖',
    category: '综合类',
    year: 2012,
    type: 'official',
    status: 'winner'
  },
  {
    id: 'award-2012-3',
    name: '最佳女配角奖',
    ceremony: '2011第1届搜狐视频电视剧盛典',
    category: '影视类',
    year: 2012,
    type: 'film',
    status: 'nomination'
  },
  // 2008
  {
    id: 'award-2008-1',
    name: '最具慈善精神新人奖',
    ceremony: '2008中信国安之夜',
    category: '公益类',
    year: 2008,
    type: 'official',
    status: 'winner'
  },
  // 2004
  {
    id: 'award-2004-1',
    name: '优秀儿童演员奖',
    ceremony: '第12届中国电影童牛奖',
    category: '影视类',
    year: 2004,
    type: 'film',
    status: 'nomination'
  }
];

export const news = [
  {
    id: '1',
    date: '2025-12-01',
    content: '新剧《生命树》即将在爱奇艺视频播出。',
    type: 'work',
  },
  {
    id: '2',
    date: '2025-11-28',
    content: '新剧《家业》即将在爱奇艺视频播出。',
    type: 'work',
  },
  {
    id: '3',
    date: '2025-11-25',
    content: '新剧《玉兰花开君再来》即将开拍，腾讯视频播出。',
    type: 'work',
  },
];

export const highlights = [
  {
    id: '1',
    title: '长相思',
    description: '播放量突破50亿，成为年度爆款剧集',
    image: '/images/works/homechangxiangsi.jpg',
    link: '/works/1',
  },
  {
    id: '2',
    title: 'Valentino品牌代言人',
    description: '正式成为Valentino品牌代言人',
    image: '/images/brands/homevalentino.jpg',
    link: '/commercial',
  },
  {
    id: '3',
    title: '年度最具影响力女演员',
    description: '荣获多项年度大奖认可',
    image: '/images/highlights/homeyingxianglinvxing.jpg',
    link: '/profile',
  },
];
